name: "虚拟门禁系统"
version: "0.1.8"
slug: "uppercoast_doorlock"
description: "仅支持麦驰可视对讲门禁系统；运行虚拟室内机、呼叫监听、接听和解锁服务。"
url: "https://github.com/CelerPi/HA-UpperCoast-DoorLock-Addon"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
host_network: true
homeassistant_api: true
options:
  building_id: "1栋A座"
  local_id: "00010116010"
  local_ip: "192.168.16.64"
  center_ip: "192.168.16.2"
  property_center_ip: "192.168.16.3"
  api_host: "0.0.0.0"
  api_port: 8099
  api_token: ""
  door_01_ip: ""
  door_02_ip: ""
  door_03_ip: ""
  door_04_ip: ""
  door_05_ip: ""
  door_06_ip: ""
  door_07_ip: ""
  door_08_ip: ""
schema:
  building_id: list(1栋A座|1栋B座|1栋C座|1栋D座|1栋E座|2栋A座|2栋B座|2栋C座)
  local_id: str
  local_ip: str
  center_ip: str
  property_center_ip: str
  api_host: str
  api_port: int(1,65535)
  api_token: password
  door_01_ip: str
  door_02_ip: str
  door_03_ip: str
  door_04_ip: str
  door_05_ip: str
  door_06_ip: str
  door_07_ip: str
  door_08_ip: str
